FROM python:3.11
WORKDIR /src
COPY . .
RUN pip install -r requirements.txt && \
    pip install pyinstaller && \
    pyinstaller --hidden-import _cffi_backend --paths ./phase_cli --name phase phase_cli/main.py
