apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phase-kubernetes-operator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "phase-kubernetes-operator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "phase-kubernetes-operator.fullname" . }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.operator.resources | nindent 12 }}
