name: "Attach Assets to Release"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  attach-to-release:
    name: Attach Assets to Release
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: phase-cli-binaries
          path: ./release

      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: phase-cli-packages
          path: ./release

      - name: Attach assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
