name: Process and Package Assets

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  process-assets:
    name: Process and Package Assets
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Process assets
        run: |
          python process_assets.py . phase-cli-release/ --version ${{ inputs.version }}

      - name: Upload processed assets
        uses: actions/upload-artifact@v4
        with:
          name: phase-cli-release
          path: ./phase-cli-release/

  attach-to-release:
    name: Attach Assets to Release
    needs: process-assets
    runs-on: ubuntu-20.04
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Download processed assets
        uses: actions/download-artifact@v4
        with:
          name: phase-cli-release
          path: ./phase-cli-release

      - name: Attach assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./phase-cli-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}